server:
  port: 3344

spring:
  application:
    name:  cloud-config-center-server   #配置中心客户端
  cloud:
    config:
      server:
        git:
          uri: git@github.com:caibixyy/springcloud-config.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支        地址：http://config-3344.com:3344/master/config-dev.yml    需修改window主机映射文件localhost  config-3344.com
      label: master
#rabbitmq相关配置
rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


